const skillsData=[
    {
        id:1,
        skillName:"HTML",
        imgsrc:"html.png"
    },
    {
        id:2,
        skillName:"CSS",
        imgsrc:"css.png"
    },
    {
        id:3,
        skillName:"JavaScript",
        imgsrc:"/javascript.png"
    },
    {
        id:4,
        skillName:"React",
        imgsrc:"/react.png"
    },
    {
        id:5,
        skillName:"Redux",
        imgsrc:"/redux.png"
    },
    {
        id:6,
        skillName:"Node",
        imgsrc:"/node.png"
    },
    {
        id:7,
        skillName:"MongoDB",
        imgsrc:"/mongodb.png"
    },
    {
        id:8,
        skillName:"Express",
        imgsrc:"/express.png"
    },
    {
        id:9,
        skillName:"Git",
        imgsrc:"/git.png"
    },
    {
        id:10,
        skillName:"GitHub",
        imgsrc:"/github.png"
    },
    {
        id:11,

        skillName:"Bootstrap",
        imgsrc:"/bootstrap.png"
    },
]
export default skillsData;